---
- name: Criar diretório kube
  file:
    path: /home/vagrant/.kube
    state: directory
    mode: '0740'
    owner: vagrant
    group: vagrant

- name: Configurar kubeconfig para o usuário vagrant
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
    mode: '0644'
