---
- name: Create Docker Registry
  docker_container:
    name: registry
    image: registry:2
    state: started
    restart_policy: always
    volumes:
      - /var/lib/registry
    ports:
      - "5000:5000"
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
