- name: Configurar Kubernetes Controller
  hosts: kubemaster01
  become: yes
  tasks:
    - include_tasks: add_repo.yml
    - include_tasks: install_packages.yml
    - include_tasks: configure_kubeconfig.yml
    - include_tasks: create_dockerregistry.yml
    - include_tasks: ingress_install.yml
    - include_tasks: running_metallb.yml
