---
- name: Change configmap kube-proxy to prepare file to metallb
  command: "export KUBECONFIG=/home/vagrant/.kube/config; kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e \"s/strictARP: false/strictARP: true/\" | kubectl apply -f - -n kube-system"

- name: Create a namespace
  community.kubernetes.k8s:
    state: present
    kubeconfig: /home/vagrant/.kube/config
    src: configure/templates/namespace.yaml
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

- name: Create a configmap
  community.kubernetes.k8s:
    state: present
    kubeconfig: /home/vagrant/.kube/config
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: metallb-system
        name: config
      data:
        config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - 192.168.15.50-192.168.15.51

- name: Create a secret
  community.kubernetes.k8s:
    state: present
    kubeconfig: /home/vagrant/.kube/config
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: memberlist
        namespace: metallb-system
      type: Opaque
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

- name: Deploy MetalLB
  community.kubernetes.k8s:
    state: present
    kubeconfig: /home/vagrant/.kube/config
    src: configure/templates/metallb.yaml
