---
- name: Modificar configmap kube-proxy para preparar arquivo para MetalLB
  command: >
    kubectl get configmap kube-proxy -n kube-system -o yaml |
    sed -e "s/strictARP: false/strictARP: true/" |
    kubectl apply -f - -n kube-system

- name: Criar namespace MetalLB
  community.kubernetes.k8s:
    state: present
    kubeconfig: /home/vagrant/.kube/config
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: metallb-system

- name: Criar configmap para MetalLB
  community.kubernetes.k8s:
    state: present
    kubeconfig: /home/vagrant/.kube/config
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: metallb-system
        name: config
      data:
        config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - 192.168.16.50-192.168.16.51

- name: Criar segredo para MetalLB
  community.kubernetes.k8s:
    state: present
    kubeconfig: /home/vagrant/.kube/config
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: memberlist
        namespace: metallb-system
      type: Opaque
      data:
        secretkey: JChvcGVuc3NsIHJhbmQgLWJhc2U2NCAxMjgp

- name: Deploy MetalLB
  community.kubernetes.k8s:
    state: present
    kubeconfig: /home/vagrant/.kube/config
    src: configure/templates/metallb.yaml
